apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-ml
  template:
    metadata:
      labels:
        app: healthcare-ml
    spec:
      containers:
      - name: healthcare-ml
        image: healthcare-ml
        imagePullPolicy: Never
        ports:
        - containerPort: 8000